version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
    tags:
      prefix:
        - v
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@dotnet
        name: build_dotnet
        displayName: .NET Core 构建
        dotnetVersion: '10.0'
        commands:
          - VERSION=$(git describe --tags --exact-match 2>/dev/null | sed 's/^v//'); [ -z "$VERSION" ] && VERSION="0.0.0"
          - dotnet build --configuration Release -p:Version=${VERSION} -p:EnableWindowsTargeting=true
          - dotnet publish -c Release --p:OutputPath=./out/   -p:PublishSingleFile=true -p:SelfContained=true -p:RuntimeIdentifier=win-x64 -p:Version=${VERSION}  -p:EnableWindowsTargeting=true
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./out/publish/
        caches:
          - ~/.nuget/packages
        notify: []
        strategy:
          retry: '0'
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: TrafficPilot
        notify: []
        strategy:
          retry: '0'
        dependsOn: build_dotnet
  - name: release
    displayName: 发布
    strategy: naturally
    trigger: auto
    steps:
      - step: release@gitee
        name: release_gitee
        displayName: Gitee Release
        releaseName: ${GITEE_BRANCH}
        description: ${GITEE_BRANCH}
        tagName: ${GITEE_BRANCH}
        upstreamArtifact:
          - BUILD_ARTIFACT
        assertFiles:
          - TrafficPilot.exe
        prerelease: true
        allowUpdate: true
        notify: []
        strategy:
          retry: '0'
